/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  JinRyuu.JRMCore.JRMCoreSafe
 *  JinRyuu.JRMCore.blocks.BlocksJRMC
 *  net.minecraft.block.Block
 *  net.minecraft.block.material.Material
 *  net.minecraft.entity.Entity
 *  net.minecraft.world.World
 *  net.minecraft.world.gen.feature.WorldGenerator
 */
package JinRyuu.DragonBC.common.Villages;

import JinRyuu.DragonBC.common.Npcs.EntityMasterEnma;
import JinRyuu.DragonBC.common.Villages.ChkInStP2;
import JinRyuu.DragonBC.common.mod_DragonBC;
import JinRyuu.JRMCore.JRMCoreSafe;
import JinRyuu.JRMCore.blocks.BlocksJRMC;
import java.util.Random;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.entity.Entity;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

public class ChkInSt
extends WorldGenerator {
    public Block c = BlocksJRMC.BlockColoredStone;

    protected void b(World par1World, int par2, int par3, int par4, Block par5) {
        this.func_150516_a(par1World, par2, par3, par4, par5, 0);
    }

    protected void bm(World par1World, int par2, int par3, int par4, Block par5, int par6) {
        this.func_150516_a(par1World, par2, par3, par4, par5, par6);
    }

    public boolean func_76484_a(World w, Random rand, int i, int j, int k) {
        block0: {
            i = 0;
            j = 90;
            k = 0;
            JRMCoreSafe safe = new JRMCoreSafe(w);
            boolean gen = safe.isSpawn("false ", "dont", 0, safe.OWDataDir, "edp.dbc");
            boolean dont = safe.isSpawn("false", 0, safe.OWDataDir, "edp.dbc");
            int dim = w.field_73011_w.field_76574_g;
            if (w.func_147439_a(i, j, k).func_149688_o() != Material.field_151579_a || w.func_147439_a(i, j + 1, k).func_149688_o() != Material.field_151579_a || w.func_147439_a(i + 32, j + 1, k).func_149688_o() != Material.field_151579_a || w.func_147439_a(i + 32, j + 1, k + 60).func_149688_o() != Material.field_151579_a) break block0;
            safe.saveSpawnList("spwn ", safe.OWDataDir, "edp.dbc");
            mod_DragonBC.logger.info("Enma's Palace Spawned");
            this.b(w, i + 1, j + 0, k + 29, this.c);
            this.b(w, i + 1, j + 0, k + 30, this.c);
            this.b(w, i + 1, j + 0, k + 31, this.c);
            this.b(w, i + 1, j + 0, k + 32, this.c);
            this.b(w, i + 1, j + 0, k + 33, this.c);
            this.b(w, i + 1, j + 0, k + 34, this.c);
            this.b(w, i + 1, j + 0, k + 35, this.c);
            this.b(w, i + 1, j + 0, k + 36, this.c);
            this.b(w, i + 1, j + 0, k + 37, this.c);
            this.b(w, i + 1, j + 0, k + 38, this.c);
            this.b(w, i + 1, j + 0, k + 39, this.c);
            this.b(w, i + 1, j + 0, k + 40, this.c);
            this.b(w, i + 1, j + 0, k + 41, this.c);
            this.b(w, i + 1, j + 0, k + 42, this.c);
            this.b(w, i + 1, j + 0, k + 43, this.c);
            this.b(w, i + 1, j + 0, k + 44, this.c);
            this.b(w, i + 1, j + 0, k + 45, this.c);
            this.b(w, i + 1, j + 0, k + 46, this.c);
            this.b(w, i + 1, j + 0, k + 47, this.c);
            this.b(w, i + 1, j + 0, k + 48, this.c);
            this.b(w, i + 1, j + 0, k + 49, this.c);
            this.b(w, i + 1, j + 0, k + 50, this.c);
            this.b(w, i + 1, j + 0, k + 51, this.c);
            this.b(w, i + 1, j + 0, k + 52, this.c);
            this.b(w, i + 1, j + 0, k + 53, this.c);
            this.b(w, i + 1, j + 0, k + 54, this.c);
            this.b(w, i + 1, j + 0, k + 55, this.c);
            this.b(w, i + 1, j + 0, k + 56, this.c);
            this.b(w, i + 1, j + 0, k + 57, this.c);
            this.b(w, i + 1, j + 0, k + 58, this.c);
            this.b(w, i + 1, j + 0, k + 59, this.c);
            this.b(w, i + 1, j + 0, k + 60, this.c);
            this.b(w, i + 1, j + 0, k + 61, this.c);
            this.b(w, i + 1, j + 0, k + 62, this.c);
            this.b(w, i + 1, j + 0, k + 63, this.c);
            this.b(w, i + 1, j + 0, k + 64, this.c);
            this.b(w, i + 1, j + 0, k + 65, this.c);
            this.b(w, i + 1, j + 0, k + 66, this.c);
            this.b(w, i + 1, j + 0, k + 67, this.c);
            this.b(w, i + 1, j + 0, k + 68, this.c);
            this.b(w, i + 1, j + 0, k + 69, this.c);
            this.b(w, i + 1, j + 0, k + 70, this.c);
            this.b(w, i + 1, j + 0, k + 71, this.c);
            this.b(w, i + 1, j + 0, k + 72, this.c);
            this.b(w, i + 1, j + 0, k + 73, this.c);
            this.b(w, i + 1, j + 0, k + 74, this.c);
            this.b(w, i + 1, j + 0, k + 75, this.c);
            this.b(w, i + 1, j + 0, k + 76, this.c);
            this.b(w, i + 1, j + 0, k + 77, this.c);
            this.b(w, i + 1, j + 0, k + 78, this.c);
            this.b(w, i + 1, j + 0, k + 79, this.c);
            this.b(w, i + 1, j + 0, k + 80, this.c);
            this.b(w, i + 1, j + 0, k + 81, this.c);
            this.bm(w, i + 1, j + 1, k + 31, this.c, 14);
            this.bm(w, i + 1, j + 1, k + 36, this.c, 14);
            this.bm(w, i + 1, j + 1, k + 41, this.c, 14);
            this.bm(w, i + 1, j + 1, k + 46, this.c, 14);
            this.bm(w, i + 1, j + 1, k + 51, this.c, 14);
            this.bm(w, i + 1, j + 1, k + 59, this.c, 14);
            this.bm(w, i + 1, j + 1, k + 64, this.c, 14);
            this.bm(w, i + 1, j + 1, k + 69, this.c, 14);
            this.bm(w, i + 1, j + 1, k + 74, this.c, 14);
            this.bm(w, i + 1, j + 1, k + 79, this.c, 14);
            this.b(w, i + 2, j + 0, k + 29, this.c);
            this.b(w, i + 2, j + 0, k + 30, this.c);
            this.b(w, i + 2, j + 0, k + 31, this.c);
            this.b(w, i + 2, j + 0, k + 32, this.c);
            this.b(w, i + 2, j + 0, k + 33, this.c);
            this.b(w, i + 2, j + 0, k + 34, this.c);
            this.b(w, i + 2, j + 0, k + 35, this.c);
            this.b(w, i + 2, j + 0, k + 36, this.c);
            this.b(w, i + 2, j + 0, k + 37, this.c);
            this.b(w, i + 2, j + 0, k + 38, this.c);
            this.b(w, i + 2, j + 0, k + 39, this.c);
            this.b(w, i + 2, j + 0, k + 40, this.c);
            this.b(w, i + 2, j + 0, k + 41, this.c);
            this.b(w, i + 2, j + 0, k + 42, this.c);
            this.b(w, i + 2, j + 0, k + 43, this.c);
            this.b(w, i + 2, j + 0, k + 44, this.c);
            this.b(w, i + 2, j + 0, k + 45, this.c);
            this.b(w, i + 2, j + 0, k + 46, this.c);
            this.b(w, i + 2, j + 0, k + 47, this.c);
            this.b(w, i + 2, j + 0, k + 48, this.c);
            this.b(w, i + 2, j + 0, k + 49, this.c);
            this.b(w, i + 2, j + 0, k + 50, this.c);
            this.b(w, i + 2, j + 0, k + 51, this.c);
            this.b(w, i + 2, j + 0, k + 52, this.c);
            this.b(w, i + 2, j + 0, k + 53, this.c);
            this.b(w, i + 2, j + 0, k + 54, this.c);
            this.b(w, i + 2, j + 0, k + 55, this.c);
            this.b(w, i + 2, j + 0, k + 56, this.c);
            this.b(w, i + 2, j + 0, k + 57, this.c);
            this.b(w, i + 2, j + 0, k + 58, this.c);
            this.b(w, i + 2, j + 0, k + 59, this.c);
            this.b(w, i + 2, j + 0, k + 60, this.c);
            this.b(w, i + 2, j + 0, k + 61, this.c);
            this.b(w, i + 2, j + 0, k + 62, this.c);
            this.b(w, i + 2, j + 0, k + 63, this.c);
            this.b(w, i + 2, j + 0, k + 64, this.c);
            this.b(w, i + 2, j + 0, k + 65, this.c);
            this.b(w, i + 2, j + 0, k + 66, this.c);
            this.b(w, i + 2, j + 0, k + 67, this.c);
            this.b(w, i + 2, j + 0, k + 68, this.c);
            this.b(w, i + 2, j + 0, k + 69, this.c);
            this.b(w, i + 2, j + 0, k + 70, this.c);
            this.b(w, i + 2, j + 0, k + 71, this.c);
            this.b(w, i + 2, j + 0, k + 72, this.c);
            this.b(w, i + 2, j + 0, k + 73, this.c);
            this.b(w, i + 2, j + 0, k + 74, this.c);
            this.b(w, i + 2, j + 0, k + 75, this.c);
            this.b(w, i + 2, j + 0, k + 76, this.c);
            this.b(w, i + 2, j + 0, k + 77, this.c);
            this.b(w, i + 2, j + 0, k + 78, this.c);
            this.b(w, i + 2, j + 0, k + 79, this.c);
            this.b(w, i + 2, j + 0, k + 80, this.c);
            this.b(w, i + 2, j + 0, k + 81, this.c);
            this.b(w, i + 3, j + 0, k + 29, this.c);
            this.b(w, i + 3, j + 0, k + 30, this.c);
            this.b(w, i + 3, j + 0, k + 31, this.c);
            this.b(w, i + 3, j + 0, k + 32, this.c);
            this.b(w, i + 3, j + 0, k + 33, this.c);
            this.b(w, i + 3, j + 0, k + 34, this.c);
            this.b(w, i + 3, j + 0, k + 35, this.c);
            this.b(w, i + 3, j + 0, k + 36, this.c);
            this.b(w, i + 3, j + 0, k + 37, this.c);
            this.b(w, i + 3, j + 0, k + 38, this.c);
            this.b(w, i + 3, j + 0, k + 39, this.c);
            this.b(w, i + 3, j + 0, k + 40, this.c);
            this.b(w, i + 3, j + 0, k + 41, this.c);
            this.b(w, i + 3, j + 0, k + 42, this.c);
            this.b(w, i + 3, j + 0, k + 43, this.c);
            this.b(w, i + 3, j + 0, k + 44, this.c);
            this.b(w, i + 3, j + 0, k + 45, this.c);
            this.b(w, i + 3, j + 0, k + 46, this.c);
            this.b(w, i + 3, j + 0, k + 47, this.c);
            this.b(w, i + 3, j + 0, k + 48, this.c);
            this.b(w, i + 3, j + 0, k + 49, this.c);
            this.b(w, i + 3, j + 0, k + 50, this.c);
            this.b(w, i + 3, j + 0, k + 51, this.c);
            this.b(w, i + 3, j + 0, k + 52, this.c);
            this.b(w, i + 3, j + 0, k + 53, this.c);
            this.b(w, i + 3, j + 0, k + 54, this.c);
            this.b(w, i + 3, j + 0, k + 55, this.c);
            this.b(w, i + 3, j + 0, k + 56, this.c);
            this.b(w, i + 3, j + 0, k + 57, this.c);
            this.b(w, i + 3, j + 0, k + 58, this.c);
            this.b(w, i + 3, j + 0, k + 59, this.c);
            this.b(w, i + 3, j + 0, k + 60, this.c);
            this.b(w, i + 3, j + 0, k + 61, this.c);
            this.b(w, i + 3, j + 0, k + 62, this.c);
            this.b(w, i + 3, j + 0, k + 63, this.c);
            this.b(w, i + 3, j + 0, k + 64, this.c);
            this.b(w, i + 3, j + 0, k + 65, this.c);
            this.b(w, i + 3, j + 0, k + 66, this.c);
            this.b(w, i + 3, j + 0, k + 67, this.c);
            this.b(w, i + 3, j + 0, k + 68, this.c);
            this.b(w, i + 3, j + 0, k + 69, this.c);
            this.b(w, i + 3, j + 0, k + 70, this.c);
            this.b(w, i + 3, j + 0, k + 71, this.c);
            this.b(w, i + 3, j + 0, k + 72, this.c);
            this.b(w, i + 3, j + 0, k + 73, this.c);
            this.b(w, i + 3, j + 0, k + 74, this.c);
            this.b(w, i + 3, j + 0, k + 75, this.c);
            this.b(w, i + 3, j + 0, k + 76, this.c);
            this.b(w, i + 3, j + 0, k + 77, this.c);
            this.b(w, i + 3, j + 0, k + 78, this.c);
            this.b(w, i + 3, j + 0, k + 79, this.c);
            this.b(w, i + 3, j + 0, k + 80, this.c);
            this.b(w, i + 3, j + 0, k + 81, this.c);
            this.b(w, i + 4, j + 0, k + 29, this.c);
            this.b(w, i + 4, j + 0, k + 30, this.c);
            this.b(w, i + 4, j + 0, k + 31, this.c);
            this.b(w, i + 4, j + 0, k + 32, this.c);
            this.b(w, i + 4, j + 0, k + 33, this.c);
            this.b(w, i + 4, j + 0, k + 34, this.c);
            this.b(w, i + 4, j + 0, k + 35, this.c);
            this.b(w, i + 4, j + 0, k + 36, this.c);
            this.b(w, i + 4, j + 0, k + 37, this.c);
            this.b(w, i + 4, j + 0, k + 38, this.c);
            this.b(w, i + 4, j + 0, k + 39, this.c);
            this.b(w, i + 4, j + 0, k + 40, this.c);
            this.b(w, i + 4, j + 0, k + 41, this.c);
            this.b(w, i + 4, j + 0, k + 42, this.c);
            this.b(w, i + 4, j + 0, k + 43, this.c);
            this.b(w, i + 4, j + 0, k + 44, this.c);
            this.b(w, i + 4, j + 0, k + 45, this.c);
            this.b(w, i + 4, j + 0, k + 46, this.c);
            this.b(w, i + 4, j + 0, k + 47, this.c);
            this.b(w, i + 4, j + 0, k + 48, this.c);
            this.b(w, i + 4, j + 0, k + 49, this.c);
            this.b(w, i + 4, j + 0, k + 50, this.c);
            this.b(w, i + 4, j + 0, k + 51, this.c);
            this.b(w, i + 4, j + 0, k + 52, this.c);
            this.b(w, i + 4, j + 0, k + 53, this.c);
            this.b(w, i + 4, j + 0, k + 54, this.c);
            this.b(w, i + 4, j + 0, k + 55, this.c);
            this.b(w, i + 4, j + 0, k + 56, this.c);
            this.b(w, i + 4, j + 0, k + 57, this.c);
            this.b(w, i + 4, j + 0, k + 58, this.c);
            this.b(w, i + 4, j + 0, k + 59, this.c);
            this.b(w, i + 4, j + 0, k + 60, this.c);
            this.b(w, i + 4, j + 0, k + 61, this.c);
            this.b(w, i + 4, j + 0, k + 62, this.c);
            this.b(w, i + 4, j + 0, k + 63, this.c);
            this.b(w, i + 4, j + 0, k + 64, this.c);
            this.b(w, i + 4, j + 0, k + 65, this.c);
            this.b(w, i + 4, j + 0, k + 66, this.c);
            this.b(w, i + 4, j + 0, k + 67, this.c);
            this.b(w, i + 4, j + 0, k + 68, this.c);
            this.b(w, i + 4, j + 0, k + 69, this.c);
            this.b(w, i + 4, j + 0, k + 70, this.c);
            this.b(w, i + 4, j + 0, k + 71, this.c);
            this.b(w, i + 4, j + 0, k + 72, this.c);
            this.b(w, i + 4, j + 0, k + 73, this.c);
            this.b(w, i + 4, j + 0, k + 74, this.c);
            this.b(w, i + 4, j + 0, k + 75, this.c);
            this.b(w, i + 4, j + 0, k + 76, this.c);
            this.b(w, i + 4, j + 0, k + 77, this.c);
            this.b(w, i + 4, j + 0, k + 78, this.c);
            this.b(w, i + 4, j + 0, k + 79, this.c);
            this.b(w, i + 4, j + 0, k + 80, this.c);
            this.b(w, i + 4, j + 0, k + 81, this.c);
            this.b(w, i + 5, j + 0, k + 29, this.c);
            this.b(w, i + 5, j + 0, k + 30, this.c);
            this.b(w, i + 5, j + 0, k + 31, this.c);
            this.b(w, i + 5, j + 0, k + 32, this.c);
            this.b(w, i + 5, j + 0, k + 33, this.c);
            this.b(w, i + 5, j + 0, k + 34, this.c);
            this.b(w, i + 5, j + 0, k + 35, this.c);
            this.b(w, i + 5, j + 0, k + 36, this.c);
            this.b(w, i + 5, j + 0, k + 37, this.c);
            this.b(w, i + 5, j + 0, k + 38, this.c);
            this.b(w, i + 5, j + 0, k + 39, this.c);
            this.b(w, i + 5, j + 0, k + 40, this.c);
            this.b(w, i + 5, j + 0, k + 41, this.c);
            this.b(w, i + 5, j + 0, k + 42, this.c);
            this.b(w, i + 5, j + 0, k + 43, this.c);
            this.b(w, i + 5, j + 0, k + 44, this.c);
            this.b(w, i + 5, j + 0, k + 45, this.c);
            this.b(w, i + 5, j + 0, k + 46, this.c);
            this.b(w, i + 5, j + 0, k + 47, this.c);
            this.b(w, i + 5, j + 0, k + 48, this.c);
            this.b(w, i + 5, j + 0, k + 49, this.c);
            this.b(w, i + 5, j + 0, k + 50, this.c);
            this.b(w, i + 5, j + 0, k + 51, this.c);
            this.b(w, i + 5, j + 0, k + 52, this.c);
            this.b(w, i + 5, j + 0, k + 53, this.c);
            this.b(w, i + 5, j + 0, k + 54, this.c);
            this.b(w, i + 5, j + 0, k + 55, this.c);
            this.b(w, i + 5, j + 0, k + 56, this.c);
            this.b(w, i + 5, j + 0, k + 57, this.c);
            this.b(w, i + 5, j + 0, k + 58, this.c);
            this.b(w, i + 5, j + 0, k + 59, this.c);
            this.b(w, i + 5, j + 0, k + 60, this.c);
            this.b(w, i + 5, j + 0, k + 61, this.c);
            this.b(w, i + 5, j + 0, k + 62, this.c);
            this.b(w, i + 5, j + 0, k + 63, this.c);
            this.b(w, i + 5, j + 0, k + 64, this.c);
            this.b(w, i + 5, j + 0, k + 65, this.c);
            this.b(w, i + 5, j + 0, k + 66, this.c);
            this.b(w, i + 5, j + 0, k + 67, this.c);
            this.b(w, i + 5, j + 0, k + 68, this.c);
            this.b(w, i + 5, j + 0, k + 69, this.c);
            this.b(w, i + 5, j + 0, k + 70, this.c);
            this.b(w, i + 5, j + 0, k + 71, this.c);
            this.b(w, i + 5, j + 0, k + 72, this.c);
            this.b(w, i + 5, j + 0, k + 73, this.c);
            this.b(w, i + 5, j + 0, k + 74, this.c);
            this.b(w, i + 5, j + 0, k + 75, this.c);
            this.b(w, i + 5, j + 0, k + 76, this.c);
            this.b(w, i + 5, j + 0, k + 77, this.c);
            this.b(w, i + 5, j + 0, k + 78, this.c);
            this.b(w, i + 5, j + 0, k + 79, this.c);
            this.b(w, i + 5, j + 0, k + 80, this.c);
            this.b(w, i + 5, j + 0, k + 81, this.c);
            this.bm(w, i + 5, j + 6, k + 38, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 39, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 40, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 41, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 42, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 43, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 44, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 45, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 46, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 47, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 48, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 49, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 50, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 51, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 52, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 53, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 54, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 55, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 56, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 57, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 58, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 59, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 60, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 61, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 62, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 63, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 64, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 65, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 66, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 67, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 68, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 69, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 70, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 71, this.c, 13);
            this.bm(w, i + 5, j + 6, k + 72, this.c, 13);
            this.b(w, i + 6, j + 0, k + 29, this.c);
            this.b(w, i + 6, j + 0, k + 30, this.c);
            this.b(w, i + 6, j + 0, k + 31, this.c);
            this.b(w, i + 6, j + 0, k + 32, this.c);
            this.b(w, i + 6, j + 0, k + 33, this.c);
            this.b(w, i + 6, j + 0, k + 34, this.c);
            this.b(w, i + 6, j + 0, k + 35, this.c);
            this.b(w, i + 6, j + 0, k + 36, this.c);
            this.b(w, i + 6, j + 0, k + 37, this.c);
            this.b(w, i + 6, j + 0, k + 38, this.c);
            this.b(w, i + 6, j + 0, k + 39, this.c);
            this.b(w, i + 6, j + 0, k + 40, this.c);
            this.b(w, i + 6, j + 0, k + 41, this.c);
            this.b(w, i + 6, j + 0, k + 42, this.c);
            this.b(w, i + 6, j + 0, k + 43, this.c);
            this.b(w, i + 6, j + 0, k + 44, this.c);
            this.b(w, i + 6, j + 0, k + 45, this.c);
            this.b(w, i + 6, j + 0, k + 46, this.c);
            this.b(w, i + 6, j + 0, k + 47, this.c);
            this.b(w, i + 6, j + 0, k + 48, this.c);
            this.b(w, i + 6, j + 0, k + 49, this.c);
            this.b(w, i + 6, j + 0, k + 50, this.c);
            this.b(w, i + 6, j + 0, k + 51, this.c);
            this.b(w, i + 6, j + 0, k + 52, this.c);
            this.b(w, i + 6, j + 0, k + 53, this.c);
            this.b(w, i + 6, j + 0, k + 54, this.c);
            this.b(w, i + 6, j + 0, k + 55, this.c);
            this.b(w, i + 6, j + 0, k + 56, this.c);
            this.b(w, i + 6, j + 0, k + 57, this.c);
            this.b(w, i + 6, j + 0, k + 58, this.c);
            this.b(w, i + 6, j + 0, k + 59, this.c);
            this.b(w, i + 6, j + 0, k + 60, this.c);
            this.b(w, i + 6, j + 0, k + 61, this.c);
            this.b(w, i + 6, j + 0, k + 62, this.c);
            this.b(w, i + 6, j + 0, k + 63, this.c);
            this.b(w, i + 6, j + 0, k + 64, this.c);
            this.b(w, i + 6, j + 0, k + 65, this.c);
            this.b(w, i + 6, j + 0, k + 66, this.c);
            this.b(w, i + 6, j + 0, k + 67, this.c);
            this.b(w, i + 6, j + 0, k + 68, this.c);
            this.b(w, i + 6, j + 0, k + 69, this.c);
            this.b(w, i + 6, j + 0, k + 70, this.c);
            this.b(w, i + 6, j + 0, k + 71, this.c);
            this.b(w, i + 6, j + 0, k + 72, this.c);
            this.b(w, i + 6, j + 0, k + 73, this.c);
            this.b(w, i + 6, j + 0, k + 74, this.c);
            this.b(w, i + 6, j + 0, k + 75, this.c);
            this.b(w, i + 6, j + 0, k + 76, this.c);
            this.b(w, i + 6, j + 0, k + 77, this.c);
            this.b(w, i + 6, j + 0, k + 78, this.c);
            this.b(w, i + 6, j + 0, k + 79, this.c);
            this.b(w, i + 6, j + 0, k + 80, this.c);
            this.b(w, i + 6, j + 0, k + 81, this.c);
            this.bm(w, i + 6, j + 1, k + 39, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 40, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 41, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 42, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 43, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 44, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 45, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 46, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 47, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 48, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 49, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 50, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 51, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 52, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 53, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 57, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 58, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 59, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 60, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 61, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 62, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 63, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 64, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 65, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 66, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 67, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 68, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 69, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 70, this.c, 14);
            this.bm(w, i + 6, j + 1, k + 71, this.c, 14);
            this.b(w, i + 6, j + 2, k + 39, this.c);
            this.b(w, i + 6, j + 2, k + 40, this.c);
            this.b(w, i + 6, j + 2, k + 41, this.c);
            this.b(w, i + 6, j + 2, k + 42, this.c);
            this.b(w, i + 6, j + 2, k + 43, this.c);
            this.b(w, i + 6, j + 2, k + 44, this.c);
            this.b(w, i + 6, j + 2, k + 45, this.c);
            this.b(w, i + 6, j + 2, k + 46, this.c);
            this.b(w, i + 6, j + 2, k + 47, this.c);
            this.b(w, i + 6, j + 2, k + 48, this.c);
            this.b(w, i + 6, j + 2, k + 49, this.c);
            this.b(w, i + 6, j + 2, k + 50, this.c);
            this.b(w, i + 6, j + 2, k + 51, this.c);
            this.b(w, i + 6, j + 2, k + 52, this.c);
            this.bm(w, i + 6, j + 2, k + 53, this.c, 14);
            this.bm(w, i + 6, j + 2, k + 57, this.c, 14);
            this.b(w, i + 6, j + 2, k + 58, this.c);
            this.b(w, i + 6, j + 2, k + 59, this.c);
            this.b(w, i + 6, j + 2, k + 60, this.c);
            this.b(w, i + 6, j + 2, k + 61, this.c);
            this.b(w, i + 6, j + 2, k + 62, this.c);
            this.b(w, i + 6, j + 2, k + 63, this.c);
            this.b(w, i + 6, j + 2, k + 64, this.c);
            this.b(w, i + 6, j + 2, k + 65, this.c);
            this.b(w, i + 6, j + 2, k + 66, this.c);
            this.b(w, i + 6, j + 2, k + 67, this.c);
            this.b(w, i + 6, j + 2, k + 68, this.c);
            this.b(w, i + 6, j + 2, k + 69, this.c);
            this.b(w, i + 6, j + 2, k + 70, this.c);
            this.b(w, i + 6, j + 2, k + 71, this.c);
            this.b(w, i + 6, j + 3, k + 39, this.c);
            this.b(w, i + 6, j + 3, k + 40, this.c);
            this.b(w, i + 6, j + 3, k + 41, this.c);
            this.b(w, i + 6, j + 3, k + 42, this.c);
            this.b(w, i + 6, j + 3, k + 43, this.c);
            this.b(w, i + 6, j + 3, k + 44, this.c);
            this.b(w, i + 6, j + 3, k + 45, this.c);
            this.b(w, i + 6, j + 3, k + 46, this.c);
            this.b(w, i + 6, j + 3, k + 47, this.c);
            this.b(w, i + 6, j + 3, k + 48, this.c);
            this.b(w, i + 6, j + 3, k + 49, this.c);
            this.b(w, i + 6, j + 3, k + 50, this.c);
            this.b(w, i + 6, j + 3, k + 51, this.c);
            this.b(w, i + 6, j + 3, k + 52, this.c);
            this.bm(w, i + 6, j + 3, k + 53, this.c, 14);
            this.bm(w, i + 6, j + 3, k + 57, this.c, 14);
            this.b(w, i + 6, j + 3, k + 58, this.c);
            this.b(w, i + 6, j + 3, k + 59, this.c);
            this.b(w, i + 6, j + 3, k + 60, this.c);
            this.b(w, i + 6, j + 3, k + 61, this.c);
            this.b(w, i + 6, j + 3, k + 62, this.c);
            this.b(w, i + 6, j + 3, k + 63, this.c);
            this.b(w, i + 6, j + 3, k + 64, this.c);
            this.b(w, i + 6, j + 3, k + 65, this.c);
            this.b(w, i + 6, j + 3, k + 66, this.c);
            this.b(w, i + 6, j + 3, k + 67, this.c);
            this.b(w, i + 6, j + 3, k + 68, this.c);
            this.b(w, i + 6, j + 3, k + 69, this.c);
            this.b(w, i + 6, j + 3, k + 70, this.c);
            this.b(w, i + 6, j + 3, k + 71, this.c);
            this.b(w, i + 6, j + 4, k + 39, this.c);
            this.b(w, i + 6, j + 4, k + 40, this.c);
            this.b(w, i + 6, j + 4, k + 41, this.c);
            this.b(w, i + 6, j + 4, k + 42, this.c);
            this.b(w, i + 6, j + 4, k + 43, this.c);
            this.b(w, i + 6, j + 4, k + 44, this.c);
            this.b(w, i + 6, j + 4, k + 45, this.c);
            this.b(w, i + 6, j + 4, k + 46, this.c);
            this.b(w, i + 6, j + 4, k + 47, this.c);
            this.b(w, i + 6, j + 4, k + 48, this.c);
            this.b(w, i + 6, j + 4, k + 49, this.c);
            this.b(w, i + 6, j + 4, k + 50, this.c);
            this.b(w, i + 6, j + 4, k + 51, this.c);
            this.b(w, i + 6, j + 4, k + 52, this.c);
            this.b(w, i + 6, j + 4, k + 53, this.c);
            this.bm(w, i + 6, j + 4, k + 54, this.c, 14);
            this.bm(w, i + 6, j + 4, k + 56, this.c, 14);
            this.b(w, i + 6, j + 4, k + 57, this.c);
            this.b(w, i + 6, j + 4, k + 58, this.c);
            this.b(w, i + 6, j + 4, k + 59, this.c);
            this.b(w, i + 6, j + 4, k + 60, this.c);
            this.b(w, i + 6, j + 4, k + 61, this.c);
            this.b(w, i + 6, j + 4, k + 62, this.c);
            this.b(w, i + 6, j + 4, k + 63, this.c);
            this.b(w, i + 6, j + 4, k + 64, this.c);
            this.b(w, i + 6, j + 4, k + 65, this.c);
            this.b(w, i + 6, j + 4, k + 66, this.c);
            this.b(w, i + 6, j + 4, k + 67, this.c);
            this.b(w, i + 6, j + 4, k + 68, this.c);
            this.b(w, i + 6, j + 4, k + 69, this.c);
            this.b(w, i + 6, j + 4, k + 70, this.c);
            this.b(w, i + 6, j + 4, k + 71, this.c);
            this.b(w, i + 6, j + 5, k + 39, this.c);
            this.b(w, i + 6, j + 5, k + 40, this.c);
            this.b(w, i + 6, j + 5, k + 41, this.c);
            this.b(w, i + 6, j + 5, k + 42, this.c);
            this.b(w, i + 6, j + 5, k + 43, this.c);
            this.b(w, i + 6, j + 5, k + 44, this.c);
            this.b(w, i + 6, j + 5, k + 45, this.c);
            this.b(w, i + 6, j + 5, k + 46, this.c);
            this.b(w, i + 6, j + 5, k + 47, this.c);
            this.b(w, i + 6, j + 5, k + 48, this.c);
            this.b(w, i + 6, j + 5, k + 49, this.c);
            this.b(w, i + 6, j + 5, k + 50, this.c);
            this.b(w, i + 6, j + 5, k + 51, this.c);
            this.b(w, i + 6, j + 5, k + 52, this.c);
            this.b(w, i + 6, j + 5, k + 53, this.c);
            this.b(w, i + 6, j + 5, k + 54, this.c);
            this.bm(w, i + 6, j + 5, k + 55, this.c, 14);
            this.b(w, i + 6, j + 5, k + 56, this.c);
            this.b(w, i + 6, j + 5, k + 57, this.c);
            this.b(w, i + 6, j + 5, k + 58, this.c);
            this.b(w, i + 6, j + 5, k + 59, this.c);
            this.b(w, i + 6, j + 5, k + 60, this.c);
            this.b(w, i + 6, j + 5, k + 61, this.c);
            this.b(w, i + 6, j + 5, k + 62, this.c);
            this.b(w, i + 6, j + 5, k + 63, this.c);
            this.b(w, i + 6, j + 5, k + 64, this.c);
            this.b(w, i + 6, j + 5, k + 65, this.c);
            this.b(w, i + 6, j + 5, k + 66, this.c);
            this.b(w, i + 6, j + 5, k + 67, this.c);
            this.b(w, i + 6, j + 5, k + 68, this.c);
            this.b(w, i + 6, j + 5, k + 69, this.c);
            this.b(w, i + 6, j + 5, k + 70, this.c);
            this.b(w, i + 6, j + 5, k + 71, this.c);
            this.bm(w, i + 6, j + 6, k + 38, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 39, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 40, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 41, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 42, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 43, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 44, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 45, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 46, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 47, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 48, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 49, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 50, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 51, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 52, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 53, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 54, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 55, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 56, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 57, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 58, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 59, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 60, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 61, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 62, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 63, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 64, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 65, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 66, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 67, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 68, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 69, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 70, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 71, this.c, 13);
            this.bm(w, i + 6, j + 6, k + 72, this.c, 13);
            this.b(w, i + 7, j + 0, k + 29, this.c);
            this.b(w, i + 7, j + 0, k + 30, this.c);
            this.b(w, i + 7, j + 0, k + 31, this.c);
            this.b(w, i + 7, j + 0, k + 32, this.c);
            this.b(w, i + 7, j + 0, k + 33, this.c);
            this.b(w, i + 7, j + 0, k + 34, this.c);
            this.b(w, i + 7, j + 0, k + 35, this.c);
            this.b(w, i + 7, j + 0, k + 36, this.c);
            this.b(w, i + 7, j + 0, k + 37, this.c);
            this.b(w, i + 7, j + 0, k + 38, this.c);
            this.b(w, i + 7, j + 0, k + 39, this.c);
            this.bm(w, i + 7, j + 0, k + 40, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 41, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 42, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 43, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 44, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 45, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 46, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 47, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 48, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 49, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 50, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 51, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 52, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 53, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 54, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 55, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 56, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 57, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 58, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 59, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 60, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 61, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 62, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 63, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 64, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 65, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 66, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 67, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 68, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 69, this.c, 12);
            this.bm(w, i + 7, j + 0, k + 70, this.c, 12);
            this.b(w, i + 7, j + 0, k + 71, this.c);
            this.b(w, i + 7, j + 0, k + 72, this.c);
            this.b(w, i + 7, j + 0, k + 73, this.c);
            this.b(w, i + 7, j + 0, k + 74, this.c);
            this.b(w, i + 7, j + 0, k + 75, this.c);
            this.b(w, i + 7, j + 0, k + 76, this.c);
            this.b(w, i + 7, j + 0, k + 77, this.c);
            this.b(w, i + 7, j + 0, k + 78, this.c);
            this.b(w, i + 7, j + 0, k + 79, this.c);
            this.b(w, i + 7, j + 0, k + 80, this.c);
            this.b(w, i + 7, j + 0, k + 81, this.c);
            this.bm(w, i + 7, j + 1, k + 39, this.c, 14);
            this.bm(w, i + 7, j + 1, k + 71, this.c, 14);
            this.b(w, i + 7, j + 2, k + 39, this.c);
            this.b(w, i + 7, j + 2, k + 71, this.c);
            this.b(w, i + 7, j + 3, k + 39, this.c);
            this.b(w, i + 7, j + 3, k + 71, this.c);
            this.b(w, i + 7, j + 4, k + 39, this.c);
            this.b(w, i + 7, j + 4, k + 71, this.c);
            this.b(w, i + 7, j + 5, k + 39, this.c);
            this.b(w, i + 7, j + 5, k + 71, this.c);
            this.bm(w, i + 7, j + 6, k + 38, this.c, 13);
            this.bm(w, i + 7, j + 6, k + 39, this.c, 13);
            this.bm(w, i + 7, j + 6, k + 40, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 41, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 42, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 43, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 44, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 45, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 46, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 47, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 48, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 49, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 50, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 51, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 52, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 53, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 54, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 55, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 56, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 57, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 58, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 59, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 60, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 61, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 62, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 63, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 64, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 65, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 66, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 67, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 68, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 69, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 70, this.c, 12);
            this.bm(w, i + 7, j + 6, k + 71, this.c, 13);
            this.bm(w, i + 7, j + 6, k + 72, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 40, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 41, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 42, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 43, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 44, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 45, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 46, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 47, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 48, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 49, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 50, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 51, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 52, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 53, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 54, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 55, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 56, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 57, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 58, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 59, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 60, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 61, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 62, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 63, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 64, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 65, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 66, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 67, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 68, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 69, this.c, 13);
            this.bm(w, i + 7, j + 7, k + 70, this.c, 13);
            this.bm(w, i + 8, j + 0, k + 3, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 4, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 5, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 6, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 7, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 8, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 9, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 10, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 11, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 12, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 13, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 14, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 15, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 16, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 17, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 18, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 19, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 20, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 21, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 22, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 23, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 24, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 25, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 26, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 27, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 28, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 29, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 30, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 31, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 32, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 33, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 34, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 35, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 36, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 37, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 38, this.c, 14);
            this.b(w, i + 8, j + 0, k + 39, this.c);
            this.bm(w, i + 8, j + 0, k + 40, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 41, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 42, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 43, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 44, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 45, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 46, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 47, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 48, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 49, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 50, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 51, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 52, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 53, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 54, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 55, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 56, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 57, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 58, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 59, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 60, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 61, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 62, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 63, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 64, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 65, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 66, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 67, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 68, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 69, this.c, 12);
            this.bm(w, i + 8, j + 0, k + 70, this.c, 12);
            this.b(w, i + 8, j + 0, k + 71, this.c);
            this.bm(w, i + 8, j + 0, k + 72, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 73, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 74, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 75, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 76, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 77, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 78, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 79, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 80, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 81, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 82, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 83, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 84, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 85, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 86, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 87, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 88, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 89, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 90, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 91, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 92, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 93, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 94, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 95, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 96, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 97, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 98, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 99, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 100, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 101, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 102, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 103, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 104, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 105, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 106, this.c, 14);
            this.bm(w, i + 8, j + 0, k + 107, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 3, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 4, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 5, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 6, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 7, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 8, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 9, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 10, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 11, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 12, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 13, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 14, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 15, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 16, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 17, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 18, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 19, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 20, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 21, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 22, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 23, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 24, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 25, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 26, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 27, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 28, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 29, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 30, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 31, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 32, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 33, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 34, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 35, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 36, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 37, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 38, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 39, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 71, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 72, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 73, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 74, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 75, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 76, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 77, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 78, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 79, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 80, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 81, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 82, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 83, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 84, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 85, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 86, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 87, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 88, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 89, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 90, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 91, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 92, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 93, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 94, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 95, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 96, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 97, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 98, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 99, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 100, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 101, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 102, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 103, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 104, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 105, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 106, this.c, 14);
            this.bm(w, i + 8, j + 1, k + 107, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 3, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 4, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 5, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 6, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 7, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 8, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 9, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 10, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 11, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 12, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 13, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 14, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 15, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 16, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 17, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 18, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 19, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 20, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 21, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 22, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 23, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 24, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 25, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 26, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 27, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 28, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 29, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 30, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 31, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 32, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 33, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 34, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 35, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 36, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 37, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 38, this.c, 14);
            this.b(w, i + 8, j + 2, k + 39, this.c);
            this.b(w, i + 8, j + 2, k + 71, this.c);
            this.bm(w, i + 8, j + 2, k + 72, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 73, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 74, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 75, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 76, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 77, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 78, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 79, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 80, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 81, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 82, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 83, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 84, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 85, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 86, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 87, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 88, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 89, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 90, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 91, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 92, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 93, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 94, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 95, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 96, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 97, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 98, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 99, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 100, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 101, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 102, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 103, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 104, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 105, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 106, this.c, 14);
            this.bm(w, i + 8, j + 2, k + 107, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 3, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 4, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 5, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 6, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 7, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 8, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 9, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 10, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 11, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 12, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 13, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 14, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 15, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 16, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 17, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 18, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 19, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 20, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 21, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 22, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 23, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 24, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 25, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 26, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 27, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 28, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 29, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 30, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 31, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 32, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 33, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 34, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 35, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 36, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 37, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 38, this.c, 14);
            this.b(w, i + 8, j + 3, k + 39, this.c);
            this.b(w, i + 8, j + 3, k + 71, this.c);
            this.bm(w, i + 8, j + 3, k + 72, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 73, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 74, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 75, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 76, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 77, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 78, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 79, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 80, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 81, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 82, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 83, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 84, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 85, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 86, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 87, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 88, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 89, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 90, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 91, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 92, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 93, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 94, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 95, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 96, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 97, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 98, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 99, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 100, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 101, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 102, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 103, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 104, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 105, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 106, this.c, 14);
            this.bm(w, i + 8, j + 3, k + 107, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 3, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 4, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 5, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 6, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 7, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 8, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 9, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 10, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 11, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 12, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 13, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 14, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 15, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 16, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 17, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 18, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 19, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 20, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 21, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 22, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 23, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 24, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 25, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 26, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 27, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 28, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 29, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 30, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 31, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 32, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 33, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 34, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 35, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 36, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 37, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 38, this.c, 14);
            this.b(w, i + 8, j + 4, k + 39, this.c);
            this.b(w, i + 8, j + 4, k + 71, this.c);
            this.bm(w, i + 8, j + 4, k + 72, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 73, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 74, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 75, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 76, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 77, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 78, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 79, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 80, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 81, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 82, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 83, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 84, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 85, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 86, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 87, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 88, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 89, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 90, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 91, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 92, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 93, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 94, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 95, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 96, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 97, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 98, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 99, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 100, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 101, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 102, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 103, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 104, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 105, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 106, this.c, 14);
            this.bm(w, i + 8, j + 4, k + 107, this.c, 14);
            this.b(w, i + 8, j + 5, k + 39, this.c);
            this.b(w, i + 8, j + 5, k + 71, this.c);
            this.bm(w, i + 8, j + 6, k + 38, this.c, 13);
            this.bm(w, i + 8, j + 6, k + 39, this.c, 13);
            this.bm(w, i + 8, j + 6, k + 40, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 41, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 42, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 43, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 44, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 45, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 46, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 47, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 48, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 49, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 50, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 51, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 52, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 53, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 54, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 55, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 56, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 57, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 58, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 59, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 60, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 61, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 62, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 63, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 64, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 65, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 66, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 67, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 68, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 69, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 70, this.c, 12);
            this.bm(w, i + 8, j + 6, k + 71, this.c, 13);
            this.bm(w, i + 8, j + 6, k + 72, this.c, 13);
            this.bm(w, i + 8, j + 7, k + 40, this.c, 13);
            this.bm(w, i + 8, j + 7, k + 70, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 41, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 42, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 43, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 44, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 45, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 46, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 47, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 48, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 49, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 50, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 51, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 52, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 53, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 54, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 55, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 56, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 57, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 58, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 59, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 60, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 61, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 62, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 63, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 64, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 65, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 66, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 67, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 68, this.c, 13);
            this.bm(w, i + 8, j + 8, k + 69, this.c, 13);
            this.bm(w, i + 9, j + 0, k + 3, this.c, 14);
            this.b(w, i + 9, j + 0, k + 39, this.c);
            this.bm(w, i + 9, j + 0, k + 40, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 41, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 42, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 43, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 44, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 45, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 46, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 47, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 48, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 49, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 50, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 51, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 52, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 53, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 54, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 55, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 56, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 57, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 58, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 59, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 60, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 61, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 62, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 63, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 64, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 65, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 66, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 67, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 68, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 69, this.c, 12);
            this.bm(w, i + 9, j + 0, k + 70, this.c, 12);
            this.b(w, i + 9, j + 0, k + 71, this.c);
            this.bm(w, i + 9, j + 0, k + 107, this.c, 14);
            this.bm(w, i + 9, j + 1, k + 3, this.c, 14);
            this.bm(w, i + 9, j + 1, k + 39, this.c, 14);
            this.bm(w, i + 9, j + 1, k + 71, this.c, 14);
            this.bm(w, i + 9, j + 1, k + 107, this.c, 14);
            this.bm(w, i + 9, j + 2, k + 3, this.c, 14);
            this.b(w, i + 9, j + 2, k + 39, this.c);
            this.b(w, i + 9, j + 2, k + 71, this.c);
            this.bm(w, i + 9, j + 2, k + 107, this.c, 14);
            this.bm(w, i + 9, j + 3, k + 3, this.c, 14);
            this.b(w, i + 9, j + 3, k + 39, this.c);
            this.b(w, i + 9, j + 3, k + 71, this.c);
            this.bm(w, i + 9, j + 3, k + 107, this.c, 14);
            this.bm(w, i + 9, j + 4, k + 3, this.c, 14);
            this.b(w, i + 9, j + 4, k + 39, this.c);
            this.b(w, i + 9, j + 4, k + 71, this.c);
            this.bm(w, i + 9, j + 4, k + 107, this.c, 14);
            this.b(w, i + 9, j + 5, k + 39, this.c);
            this.b(w, i + 9, j + 5, k + 71, this.c);
            this.bm(w, i + 9, j + 6, k + 38, this.c, 13);
            this.bm(w, i + 9, j + 6, k + 39, this.c, 13);
            this.bm(w, i + 9, j + 6, k + 40, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 41, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 42, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 43, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 44, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 45, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 46, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 47, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 48, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 49, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 50, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 51, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 52, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 53, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 54, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 55, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 56, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 57, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 58, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 59, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 60, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 61, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 62, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 63, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 64, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 65, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 66, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 67, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 68, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 69, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 70, this.c, 12);
            this.bm(w, i + 9, j + 6, k + 71, this.c, 13);
            this.bm(w, i + 9, j + 6, k + 72, this.c, 13);
            this.bm(w, i + 9, j + 7, k + 40, this.c, 13);
            this.bm(w, i + 9, j + 7, k + 70, this.c, 13);
            this.bm(w, i + 9, j + 8, k + 41, this.c, 13);
            this.bm(w, i + 9, j + 8, k + 69, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 42, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 43, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 44, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 45, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 46, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 47, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 48, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 49, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 50, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 51, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 52, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 53, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 54, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 55, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 56, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 57, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 58, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 59, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 60, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 61, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 62, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 63, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 64, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 65, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 66, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 67, this.c, 13);
            this.bm(w, i + 9, j + 9, k + 68, this.c, 13);
            this.bm(w, i + 10, j + 0, k + 3, this.c, 14);
            this.b(w, i + 10, j + 0, k + 39, this.c);
            this.bm(w, i + 10, j + 0, k + 40, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 41, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 42, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 43, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 44, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 45, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 46, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 47, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 48, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 49, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 50, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 51, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 52, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 53, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 54, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 55, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 56, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 57, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 58, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 59, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 60, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 61, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 62, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 63, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 64, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 65, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 66, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 67, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 68, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 69, this.c, 12);
            this.bm(w, i + 10, j + 0, k + 70, this.c, 12);
            this.b(w, i + 10, j + 0, k + 71, this.c);
            this.bm(w, i + 10, j + 0, k + 107, this.c, 14);
            this.bm(w, i + 10, j + 1, k + 3, this.c, 14);
            this.bm(w, i + 10, j + 1, k + 39, this.c, 14);
            this.bm(w, i + 10, j + 1, k + 71, this.c, 14);
            this.bm(w, i + 10, j + 1, k + 107, this.c, 14);
            this.bm(w, i + 10, j + 2, k + 3, this.c, 14);
            this.b(w, i + 10, j + 2, k + 39, this.c);
            this.b(w, i + 10, j + 2, k + 71, this.c);
            this.bm(w, i + 10, j + 2, k + 107, this.c, 14);
            this.bm(w, i + 10, j + 3, k + 3, this.c, 14);
            this.b(w, i + 10, j + 3, k + 39, this.c);
            this.b(w, i + 10, j + 3, k + 71, this.c);
            this.bm(w, i + 10, j + 3, k + 107, this.c, 14);
            this.bm(w, i + 10, j + 4, k + 3, this.c, 14);
            this.b(w, i + 10, j + 4, k + 39, this.c);
            this.b(w, i + 10, j + 4, k + 71, this.c);
            this.bm(w, i + 10, j + 4, k + 107, this.c, 14);
            this.b(w, i + 10, j + 5, k + 39, this.c);
            this.b(w, i + 10, j + 5, k + 71, this.c);
            this.bm(w, i + 10, j + 6, k + 38, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 39, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 40, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 41, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 42, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 43, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 44, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 45, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 46, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 47, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 48, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 49, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 50, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 51, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 52, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 53, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 54, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 55, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 56, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 57, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 58, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 59, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 60, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 61, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 62, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 63, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 64, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 65, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 66, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 67, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 68, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 69, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 70, this.c, 12);
            this.bm(w, i + 10, j + 6, k + 71, this.c, 13);
            this.bm(w, i + 10, j + 6, k + 72, this.c, 13);
            this.bm(w, i + 10, j + 7, k + 40, this.c, 13);
            this.bm(w, i + 10, j + 7, k + 70, this.c, 13);
            this.bm(w, i + 10, j + 8, k + 41, this.c, 13);
            this.bm(w, i + 10, j + 8, k + 69, this.c, 13);
            this.bm(w, i + 10, j + 9, k + 42, this.c, 13);
            this.bm(w, i + 10, j + 9, k + 68, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 43, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 44, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 45, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 46, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 47, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 48, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 49, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 50, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 51, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 52, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 53, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 54, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 55, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 56, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 57, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 58, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 59, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 60, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 61, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 62, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 63, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 64, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 65, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 66, this.c, 13);
            this.bm(w, i + 10, j + 10, k + 67, this.c, 13);
            this.bm(w, i + 11, j + 0, k + 3, this.c, 14);
            this.b(w, i + 11, j + 0, k + 39, this.c);
            this.bm(w, i + 11, j + 0, k + 40, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 41, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 42, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 43, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 44, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 45, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 46, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 47, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 48, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 49, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 50, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 51, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 52, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 53, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 54, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 55, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 56, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 57, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 58, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 59, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 60, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 61, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 62, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 63, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 64, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 65, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 66, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 67, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 68, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 69, this.c, 12);
            this.bm(w, i + 11, j + 0, k + 70, this.c, 12);
            this.b(w, i + 11, j + 0, k + 71, this.c);
            this.bm(w, i + 11, j + 0, k + 107, this.c, 14);
            this.bm(w, i + 11, j + 1, k + 3, this.c, 14);
            this.bm(w, i + 11, j + 1, k + 39, this.c, 14);
            this.bm(w, i + 11, j + 1, k + 71, this.c, 14);
            this.bm(w, i + 11, j + 1, k + 107, this.c, 14);
            this.bm(w, i + 11, j + 2, k + 3, this.c, 14);
            this.b(w, i + 11, j + 2, k + 39, this.c);
            this.b(w, i + 11, j + 2, k + 71, this.c);
            this.bm(w, i + 11, j + 2, k + 107, this.c, 14);
            this.bm(w, i + 11, j + 3, k + 3, this.c, 14);
            this.b(w, i + 11, j + 3, k + 39, this.c);
            this.b(w, i + 11, j + 3, k + 71, this.c);
            this.bm(w, i + 11, j + 3, k + 107, this.c, 14);
            this.bm(w, i + 11, j + 4, k + 3, this.c, 14);
            this.b(w, i + 11, j + 4, k + 39, this.c);
            this.b(w, i + 11, j + 4, k + 71, this.c);
            this.bm(w, i + 11, j + 4, k + 107, this.c, 14);
            this.b(w, i + 11, j + 5, k + 39, this.c);
            this.b(w, i + 11, j + 5, k + 71, this.c);
            this.bm(w, i + 11, j + 6, k + 38, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 39, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 40, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 41, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 42, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 43, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 44, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 45, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 46, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 47, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 48, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 49, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 50, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 51, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 52, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 53, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 54, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 55, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 56, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 57, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 58, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 59, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 60, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 61, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 62, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 63, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 64, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 65, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 66, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 67, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 68, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 69, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 70, this.c, 12);
            this.bm(w, i + 11, j + 6, k + 71, this.c, 13);
            this.bm(w, i + 11, j + 6, k + 72, this.c, 13);
            this.bm(w, i + 11, j + 7, k + 40, this.c, 13);
            this.bm(w, i + 11, j + 7, k + 70, this.c, 13);
            this.bm(w, i + 11, j + 8, k + 41, this.c, 13);
            this.bm(w, i + 11, j + 8, k + 69, this.c, 13);
            this.bm(w, i + 11, j + 9, k + 42, this.c, 13);
            this.bm(w, i + 11, j + 9, k + 68, this.c, 13);
            this.bm(w, i + 11, j + 10, k + 43, this.c, 13);
            this.bm(w, i + 11, j + 10, k + 67, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 44, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 45, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 46, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 47, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 48, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 49, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 50, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 51, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 52, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 53, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 54, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 55, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 56, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 57, this.c, 13);
            this.bm(w, i + 11, j + 11, k + 58, this.c, 13);
            ChkInStP2 p2 = new ChkInStP2();
            p2.generate2(w, rand, i, j, k);
            EntityMasterEnma namekian03 = new EntityMasterEnma(w);
            namekian03.func_70029_a(w);
            namekian03.func_70012_b(75.0, 91.0, 53.0, 0.0f, 0.0f);
            w.func_72838_d((Entity)namekian03);
        }
        return true;
    }
}
